version: '3.8'

services:
  test-db:
    image: postgres:13
    container_name: dashtrack-test-db
    environment:
      POSTGRES_USER: dashtrack_user
      POSTGRES_PASSWORD: dashtrack_password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashtrack_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: dashtrack-test-runner
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      - TEST_DB_HOST=test-db
      - TEST_DB_PORT=5432
      - TEST_DB_USER=dashtrack_user
      - TEST_DB_PASSWORD=dashtrack_password
      - GO_ENV=test
    volumes:
      - .:/app
      - /app/tmp
    working_dir: /app
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        echo 'Running tests...' &&
        go test -v ./... -coverprofile=coverage.out &&
        go tool cover -html=coverage.out -o coverage.html &&
        echo 'Tests completed!'
      "

volumes:
  test_postgres_data: