version: '3.8'

networks:
  dashtrack_dashtrack_network:
    external: true

services:
  # Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    container_name: dashtrack-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts:/etc/prometheus/alerts
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - dashtrack_dashtrack_network

  grafana:
    image: grafana/grafana:latest
    container_name: dashtrack-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - dashtrack_dashtrack_network
    depends_on:
      - prometheus

  # Log aggregation
  loki:
    image: grafana/loki:2.9.0
    container_name: dashtrack-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - dashtrack_dashtrack_network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: dashtrack-promtail
    volumes:
      - ./monitoring/promtail.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail_data:/tmp
    command:
      - -config.file=/etc/promtail/config.yml
    networks:
      - dashtrack_dashtrack_network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  promtail_data:
